version: 2

models:
  - name: stg_countries
  # staging countries table
    description: This contains the countries and nationalities
    columns:
      - name: country
        tests:
          - not_null
  - name: stg_food
  # staging food table
    description: This contains the food related data
    columns:
      - name: id
        description: 'PK: must be unique and not null'
        tests:
          - unique
          - not_null
  - name: stg_menu
  # staging menu table
    description: contains information about the menus of different restaurants on the app.
    columns:
      - name: id
        description: 'PK: only non-null values accepted'
        tests:
          - not_null
  - name: stg_orders
  # staging orders table
    description: contains information about the orders placed by users on the app.
    columns:
      - name: order_date
        description: 'only non-null values accepted'
        tests:
          - not_null
      - name: currency
        description: 'only accepted value is INR'
        tests:
          - accepted_values:
              values:
                - "INR"
  - name: stg_restaurant
  # staging restaurants table
    description: contains information about the restaurants available on the app
    columns:
      - name: id
        tests:
          - unique
          - not_null
  - name: stg_users
  # staging users table
    description: contains credentials about the users registered on the app
    columns:
      - name: id
        description: 'PK: must be unique and not null'
        tests:
          - unique
          - not_null
      - name: gender
        description: "only accepted values are 'male' and 'female'"
        tests:
          - accepted_values:
              values:
                - "male"
                - "female"
      - name: occupation
        description: 'only accepted values are "Self Employed", "House Wife", "Student", "Employee"'
        tests:
          - accepted_values:
              values:
                - "Self Employed"
                - "House Wife"
                - "Student"
                - "Employee"
      - name: edu_q
        description: 'only accepted values are "Post Graduate", "Graduate", "Uneducated", "High School", "Ph.D"'
        tests:
          - accepted_values:
              values:
                - "Post Graduate"
                - "Graduate"
                - "Uneducated"
                - "High School" 
                - "Ph.D"